Output script errors on standard error

diff --git a/create_prototype b/create_prototype
--- a/create_prototype
+++ b/create_prototype
@@ -6,7 +6,7 @@ PROTOTYPE_NAME="$1"
 HEROKU_REMOTE="heroku-$PROTOTYPE_NAME"
 
 if [ -z $PROTOTYPE_NAME ]; then
-  echo "ERROR: You must specify a prototype name, e.g. $ create_prototype my-fancy-prototype"
+  >&2 echo "ERROR: You must specify a prototype name, e.g. $ create_prototype my-fancy-prototype"
   exit 1
 fi
 
diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -6,12 +6,12 @@ CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
 HEROKU_REMOTE="heroku-$CURRENT_BRANCH"
 
 if [ -z "$CURRENT_BRANCH" ]; then
-  echo "ERROR: Couldn't determine current branch."
+  >&2 echo "ERROR: Couldn't determine current branch."
   exit 1
 fi
 
 if [ -z "$HEROKU_REMOTE" ]; then
-  echo "ERROR: Couldn't determine heroku remote."
+  >&2 echo "ERROR: Couldn't determine heroku remote."
   exit 1
 fi
 
